### ISSUE TITLE
Provide a network to host.evacuate

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xen-api#4337]
Hi there,

When you do a `host.evacuate`, it will use the management network by default. However, storage network could be faster to do it (often 1G vs 10G). If `host.evacuate` could have an extra optional arg like a network UUID, it would be really efficient to evacuate a host on a selected network.

Another way to do it would be to have a kind of "pool wide default migration network" that will be used by all method that doesn't specific anything for VM migration inside a pool with shared storage. But the second option seems more prone to side effects than the first one.

Any opinion about this?

**Comment by robhoes** [comment]
I'd be happy for such a thing to be added. The `host.evacuate` call just does a bunch of `VM.pool_migrate` calls internally, so that is the first thing to update. It has an `options` argument, where we could accept a `network` key. It's just a matter of getting the right IP address here: https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/xapi_vm_migrate.ml#L315-L320. Then we could also add a `network` arg to `host.evacuate`.

**Comment by olivierlambert** [comment]
Okay so to recap to be sure I understand correctly:

1. We add the optional `network` parameter in `host.evacuate`
2. If the parameter is detected, it will be simply passed to every `VM.pool_migrate`
3. However, `VM.pool_migrate` doesn't accept yet such parameter. So we have to also update it.

Is that correct?

**Comment by robhoes** [comment]
Yep, so start with 3 :)

**Comment by olivierlambert** [comment]
Thanks a lot @robhoes for your quick feedback :+1:

**Comment by benjamreis** [comment]
I'm assuming the `options` argument of `pool_migrate` is an assoc list. Is that correct?

**Comment by benjamreis** [comment]
PR has been merged, I think this issue can be closed. :)

Thanks for the help! +1
